server:
  port: 8080
  center: 192.168.31.136

#nacos端口
nacos:
  port: 8848

spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: ${server.center:localhost}:${nacos.port}
    gateway:
      routes:
        - id: base_route
          uri: http://192.168.31.136:8081
          predicates:
            - Path=/base-server/**
          filters:
            - StripPrefix=1
        - id: business_route
          uri: http://192.168.31.136:8082
          predicates:
            - Path=/business-server/**
          filters:
            - StripPrefix=1